name: Openshift Mock api CI/CD
# https://github.com/redhat-actions/starter-workflows/blob/main/deployments/openshift.yml

permissions:
  contents: read
  packages: write
  id-token: write

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "golf-dev"
  OPENSHIFT_IMAGE_TAGS: ""
  OPENSHIFT_APP_PORT: ""

  IMAGE_PATH: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hydroguard-mock-api:latest
  APP_NAME: mock-api
  APP_PORT: 8080
  IMAGE_STREAM: ${{ secrets.OPENSHIFT_NAMESPACE }}/mock-api-${{ github.run_id }}

  IMAGE: ""

  IMAGE_REGISTRY: docker.io
  IMAGE_REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  REPO_OWNER:

on:
  push:
    branches: ["test-ghcr"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}           

    - name: set env vars
      run: |
        echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ github.event.repository.name }}:latest .

    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ env.REPO_OWNER }}/${{ github.event.repository.name }}:latest