name: Deploy application using private image
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME:
  # just leaver empty
  IMAGE_TAGS: ""
  APP_NAME: hydroguard-mock-api
  APP_PORT: 8080

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine image tags
        if: env.IMAGE_TAGS == ''
        run: |
          echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV

      # https://github.com/redhat-actions/buildah-build#readme
      - name: Build from Dockerfile
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}

          dockerfiles: |
            ./Dockerfile

      # https://github.com/redhat-actions/push-to-registry#readme
      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tear down
        if: always()
        run:
          oc delete all,secret --selector=${{ steps.oc-new-app.outputs.selector }} -n ${{ secrets.OPENSHIFT_NAMESPACE }}

    deploy:
      name: deploy environment
      runs-on: ubuntu-latest
      needs: build-and-push-image

      steps:
        - uses: actions/checkout@v4

        # https://github.com/redhat-actions/oc-login#readme
        - name: OpenShift login
          uses: redhat-actions/oc-login@v1
          with:
            openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
            openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
            insecure_skip_tls_verify: true
            namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

        - name: Deploy/Update application
          run: |
            oc apply -f deployment.yml -n golf-dev
          env:
            APP_NAME: ${{ env.APP_NAME }}
            IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAGS }}
