name: MockAPI Deploy
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME:
  # just leaver empty
  IMAGE_TAGS: ""
  APP_NAME: hydroguard-mock-api
  APP_PORT: 8080

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine image tags
        if: env.IMAGE_TAGS == ''
        run: |
          echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV

      # https://github.com/redhat-actions/buildah-build#readme
      - name: Build from Dockerfile
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}

          dockerfiles: |
            ./Dockerfile

      # https://github.com/redhat-actions/push-to-registry#readme
      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy:
    name: deploy environment
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - uses: actions/checkout@v4

      - name: Install envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base

      # https://github.com/redhat-actions/oc-login#readme
      - name: OpenShift login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Set environment variables
        run: |
          echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest" >> $GITHUB_ENV

      - name: Substitute variables in deployment.yml
        run: |
          envsubst < deployment.yml > deployment_substituted.yml

      - name: Deploy/Update application
        run: |
          oc apply -f deployment_substituted.yml -n golf-dev
          oc rollout restart deploy/${{ env.APP_NAME }} -n golf-dev
   

